### ISSUE TITLE
Extra code which has no purpose

### ISSUE THREAD

**Issue by salmanm92** [siddiquefaisal10/.Net-Core-3.1-Enterprise-Application-Architecture#1]
https://github.com/siddiquefaisal10/.Net-Core-3.1-Enterprise-Application-Architecture/blob/9a3651949f1d786bf5931297e4a0d7ce3dcba3bc/TwinCityCoders.Services/Test/TestService.cs#L38

There is no need to write this code as you are checking if user==null then return null, other wise return user. what if we remove this if condition the result will be same

**Comment by siddiquefaisal10** [comment]
THanks for the help @salmanm92 . I will improve the code.
